apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<<<<<<< HEAD
  name: user-management
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: fullstack-chart
    repoURL: https://github.com/otyr-weaver/FullStack
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
=======
  name: user-management-demo
  namespace: argocd
spec:
  project: default
  source:
    chart: fullstack-chart
    path: fullstack-chart
    repoURL: https://github.com/otyr-weaver/FullStack.git
    targetRevision: HEAD
    helm:
      releaseName: fullstack-chart
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo
>>>>>>> a8258eca (Saving my local changes before rebase)
