apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management-demo
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  source:
    path: fullstack-chart-0.1.0.tgz
    repoURL: https://github.com/otyr-weaver/FullStack
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  
 
  

