apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: fullstack-chart
    repoURL: https://github.com/otyr-weaver/FullStack
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
