apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management-demo
  namespace: argocd
spec:
  project: default
  source:
    chart: fullstack-chart
    path: fullstack-chart
    repoURL: https://github.com/otyr-weaver/FullStack.git
    targetRevision: HEAD
    helm:
      releaseName: fullstack-chart
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo
