apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: argocd
spec:
  serviceName: db
  replicas: 0
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:12
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          hostPath:
            path: /mnt/db-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: argocd
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

