kubectl decribe db-0apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/db
