# FullStack App Values

frontend:
  name: frontend
  image: otyr/fullstack-frontend:latest
  replicas: 1
  containerPort: 3001
  nodePort: 30002
  serviceName: frontend-service

backend:
  name: backend
  image: otyr/fullstack-backend:latest
  replicas: 1
  containerPort: 4001
  nodePort: 32001
  serviceName: backend-service
  databaseUrl: "postgresql://postgres:postgres@db-service:5432/postgres?schema=public"

database:
  name: db
  image: postgres:12
  containerPort: 5432
  serviceName: db-service
  hostPath: /mnt/db-data
  credentials:
    user: postgres
    password: postgres
    dbName: postgres
